name: Python application test

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Check current directory
      run: ls -al
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r Flask==2.1.1
        pip install -r gunicorn==20.1.0
        pip install -r Werkzeug==2.0.1
        pip install -r pika==1.2.0
    - name: Run Tests
      run: |
        cd src
        python -m unittest test_app.py
